language: bash

sudo: false

services:
  - docker

env:
  - Dockerfile=alpine
  - Dockerfile=debian

before_script:
  - make image DOCKERFILE=$Dockerfile VERSION=test
  - make deps.bats

script:
  - make test DOCKERFILE=$Dockerfile VERSION=test

notifications:
  email:
    on_success: never
    on_failure: always
